apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyam
    environment: emiliano
  name: podyam
spec:
  containers:
  - image: nginx
    name: podyam 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
